[[project]]
name = "daqtt - Data aquisition over MQTT"
desc = "Project that lets the user easily setup an `mqtt`-broker and an instance of `influxdb`. Still WIP, but already useable. We had some embedded devices where the debugging was quite cumbersome since you had to connect some debug-cable to the device, open a terminal, create a connection, etc. Most of the devices we cared about were already outputting the data on some port, so we just build a small translation unit to forward the data coming in over the wire to an `mqtt`-broker."
tags = ["mqtt", "influxdb", "iot", "logging", "debugging"]
img = ""
links = [
  { name = "Github", url = "https://github.com/i-ilak/daqtt" },
]

[[project]]
name = "piOS - Baremetal playground for the Raspberry Pi"
desc = "In late 2022, I developed a strong interest in embedded systems, despite having minimal prior knowledge in the field. I'm a big fan of learning by doing, so I decided to read some tutorials and blog posts and just give it a shot at building a basic embedded system. I chose the Raspberry Pi as my platform due to the extensive resources available, and the fact that I already owned a couple of different models. This project was highly educational, providing me with hands-on experience in key areas such as integrating assembly language with C to initialize the CPU, writing custom allocators to manage both virtual and physical memory, and how the CPU on the Pi communicates with its GPU."
tags = ["baremetal", "raspberry_pi", "embedded", "linux", "c"]
img = ""
links = [
  { name = "Github", url = "https://github.com/i-ilak/pios" },
]

